# Generated by Django 3.0.1 on 2019-12-24 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Router Name : ')),
                ('MAC', models.CharField(max_length=50, verbose_name='Router MAC Adress : ')),
                ('static_ip', models.CharField(max_length=50, verbose_name='Router IP : ')),
                ('login_user', models.CharField(max_length=100, verbose_name='Router Admin Name : ')),
                ('login_password', models.CharField(max_length=50, verbose_name='Password : ')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
