# Generated by Django 3.0.1 on 2019-12-24 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wifi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='hostname',
            field=models.CharField(blank=True, default=None, max_length=50),
        ),
        migrations.AddField(
            model_name='device',
            name='model',
            field=models.CharField(blank=True, default=None, max_length=50),
        ),
        migrations.AddField(
            model_name='device',
            name='serial_number',
            field=models.CharField(blank=True, default=None, max_length=50),
        ),
        migrations.AddField(
            model_name='device',
            name='vendor',
            field=models.CharField(blank=True, default=None, max_length=50),
        ),
        migrations.AlterField(
            model_name='device',
            name='MAC',
            field=models.CharField(max_length=50, verbose_name='Router MAC Adress  '),
        ),
        migrations.AlterField(
            model_name='device',
            name='login_password',
            field=models.CharField(max_length=50, verbose_name='Password  '),
        ),
        migrations.AlterField(
            model_name='device',
            name='login_user',
            field=models.CharField(max_length=100, verbose_name='Router Admin Name  '),
        ),
        migrations.AlterField(
            model_name='device',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Router Name  '),
        ),
        migrations.AlterField(
            model_name='device',
            name='static_ip',
            field=models.CharField(max_length=50, verbose_name='Router IP  '),
        ),
    ]
