# Generated by Django 3.0.1 on 2019-12-24 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wifi', '0002_auto_20191224_1208'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='location',
            field=models.TextField(default='No Location'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='device',
            name='MAC',
            field=models.CharField(blank=True, default=None, max_length=50, verbose_name='Router MAC Adress  '),
        ),
    ]
