# Generated by Django 3.0.1 on 2019-12-24 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wifi', '0004_auto_20191224_1224'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='port',
            field=models.CharField(default=8728, max_length=15, verbose_name='Router Port  '),
        ),
    ]
