# Generated by Django 3.0.1 on 2019-12-28 09:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wifi', '0005_device_port'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='MAC',
            field=models.CharField(blank=True, default=None, max_length=50, verbose_name='MAC'),
        ),
        migrations.AlterField(
            model_name='device',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='device',
            name='static_ip',
            field=models.CharField(max_length=50, verbose_name='IP'),
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default=None, max_length=100, verbose_name='Client Name')),
                ('MAC', models.CharField(blank=True, default=None, max_length=50, verbose_name='MAC')),
                ('current_ip', models.CharField(blank=True, default=None, max_length=50, verbose_name='IP')),
                ('age', models.CharField(blank=True, default=None, max_length=50, verbose_name='AGE')),
                ('current_interface', models.CharField(blank=True, default=None, max_length=50, verbose_name='Interface')),
                ('data_usage', models.CharField(blank=True, default=None, max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('device_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='wifi.Device')),
            ],
        ),
    ]
