# Generated by Django 3.0.1 on 2019-12-29 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wifi', '0006_auto_20191228_1506'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='device_id',
            new_name='device',
        ),
        migrations.AlterField(
            model_name='client',
            name='data_usage',
            field=models.CharField(blank=True, default=0, max_length=50),
        ),
        migrations.AlterField(
            model_name='client',
            name='name',
            field=models.CharField(blank=True, default='No Name', max_length=100, verbose_name='Client Name'),
        ),
    ]
