# Generated by Django 3.0.1 on 2019-12-30 09:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wifi', '0008_client_is_active'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='is_active',
            new_name='accepted',
        ),
    ]
