# Generated by Django 3.0.1 on 2019-12-30 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wifi', '0009_auto_20191230_1517'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='phone',
            field=models.CharField(blank=True, default='No Phone', max_length=100),
        ),
    ]
